<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>


<div id="firstcont" style="float: right;border:solid 1px #A8A8A8;">
    <div class="ltlShadow">
    </div>
    <div class="inShadow">
    &nbsp; &nbsp;  Promotii canapea x 
    </div>
    <img src="<?php echo $this->getSkinUrl() ?>images/left/x.jpg" width="278" height="130" />
</div>
<div id="secondcont" style="float: right;border:solid 1px #A8A8A8;">
    <div class="ltlShadow">
    </div>
        <div class="inShadow">
    &nbsp; &nbsp; Promotii canapea y 
    </div>
    <img src="<?php echo $this->getSkinUrl() ?>images/left/y.jpg" width="278" height="130" />
</div>
<div id="thirdcont" style="float: right;border:solid 1px #A8A8A8;">
    <div class="ltlShadow">
    </div>
        <div class="inShadow">
        &nbsp; &nbsp; Promotii canapea z 
    </div>
    <img src="<?php echo $this->getSkinUrl() ?>images/left/z.jpg" width="278" height="130" />
</div>
