<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$categories = $this->getQuickorderData();
?>

<?php if(count($categories)): ?>
    <?php foreach($categories as $category): ?>
        <div>
            <a id="category_link_<?php echo $category->getId() ?>" onclick="getChildrenCategories('<?php echo $category->getId() ?>')" style="cursor:pointer"><img id="img_toggle_<?php echo $category->getId() ?>" src="<?php echo $this->getSkinUrl() ?>images/plus.gif" /></a>
            <span style="font-style: italic"><?php echo $category->getName() ?></span>
            <img style="display:none" id="ajax_loader_<?php echo $category->getId() ?>" src="<?php echo $this->getSkinUrl() ?>images/i_ajax_loader.gif" />
        </div>
        <div style="display:none;margin:20px" id="children_categories_<?php echo $category->getId() ?>"></div>
    <?php endforeach; ?>
<?php else: ?>
    <i>Nu exista rezultate</i>
<?php endif; ?>

