<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$categories = $this->getMainCategories();
?>

<?php if(count($categories)): ?>
    <div class="quickorder_main_categories">
        <?php foreach($categories as $category): ?>
            <div>
                <a id="category_link_<?php echo $category->getId() ?>" onclick="getChildrenCategories('<?php echo $category->getId() ?>')" style="cursor:pointer"><img id="img_toggle_<?php echo $category->getId() ?>" src="<?php echo $this->getSkinUrl() ?>images/plus.gif" /></a>
                <?php echo $category->getName() ?>
                <img style="display:none" id="ajax_loader_<?php echo $category->getId() ?>" src="<?php echo $this->getSkinUrl() ?>images/i_ajax_loader.gif" />
            </div>
            <div style="display:none;margin:20px" id="children_categories_<?php echo $category->getId() ?>"></div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>


<script type="text/javascript">
    var _base_url = '<?php echo $this->getBaseUrl() ?>';
    
    function getChildrenCategories(category_id) {
        $j('#ajax_loader_' + category_id).show();
        $j.ajax({
            url: _base_url + "quickorder/index/children/id/" + category_id,
            success: function(response){
                $j('#children_categories_' + category_id).html(response);
                $j('#children_categories_' + category_id).show();
                $j('#ajax_loader_' + category_id).hide();
                $j('#img_toggle_' + category_id).attr('src', "<?php echo $this->getSkinUrl() ?>images/minus.gif");
                $j('#category_link_' + category_id).attr('onclick','closeCategory(\'' + category_id + '\')');
            }
        });
    }
    
    function closeCategory(category_id) {
        $j('#children_categories_' + category_id).hide();
        $j('#children_categories_' + category_id).html();
        $j('#img_toggle_' + category_id).attr('src', "<?php echo $this->getSkinUrl() ?>images/plus.gif");
        $j('#category_link_' + category_id).attr('onclick','getChildrenCategories(\'' + category_id + '\')');
    }
    
    function addProductToCart(product_id) {
        $j('#product_ajax_loader_' + product_id).show();
        $j.ajax({
            url: _base_url + "quickorder/index/add/product_id/" + product_id,
            success: function(response){
                $j('#product_ajax_loader_' + product_id).hide();
                if (response != "success"){
                    alert("Eroare la adaugare in cos : \n " + response);
                    return;
                }
                alert("Produsul a fost adaugat in cos cu succes !");
            }
        });
    }
</script>