<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$collection_categories = $this->getCollectionCategories();
?>

<?php foreach($collection_categories as $category) : ?>
<div style="width:700px;">
    <div class="product-colections">
        <a href="<?php echo $this->getBaseUrl() . $category->getUrlPath() ?>">
            <img src="<?php echo $category->getImageUrl() ?>" width="180px" height="150px;"			/>
            <p style="margin-top:-20px;"><?php echo $category->getName() ?></p>
        </a>
    </div>
	</div>
<?php endforeach; ?>