<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$type_categories = $this->getTypeCategories();
?>

<?php foreach($type_categories as $category) : ?>
    <div  class="bigcolections" style="float:left;position:relative;margin:10px">
        <a href="<?php echo $this->getBaseUrl() . $category->getUrlPath() ?>">
            <img src="<?php echo $category->getImageUrl() ?>" />
        </a>
    </div>
<?php endforeach; ?>
<div style="clear: both"></div>
